# Generated by Django 3.1 on 2020-08-23 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('log_questionnaire_response_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=20)),
                ('question_id', models.BigIntegerField()),
                ('response', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'db_table': 'log_questionnaire_response',
            },
        ),
    ]
