# Generated by Django 3.1 on 2020-08-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('script_id', models.AutoField(primary_key=True, serialize=False)),
                ('script_title', models.CharField(max_length=100)),
                ('download_link', models.CharField(max_length=500)),
                ('raw_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'scripts',
            },
        ),
    ]
