# Generated by Django 3.1 on 2020-08-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('log_token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100)),
                ('token_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'log_token',
            },
        ),
    ]
