# Generated by Django 3.1 on 2020-08-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='token',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
